# Generated by Django 3.2.16 on 2024-02-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='sNameF', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='sNameL', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='eEmail', max_length=80, null=True)),
                ('phone', models.CharField(db_column='sPhone', max_length=20)),
                ('lead_status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('closed', 'Closed')], db_column='sLedStats', max_length=50)),
                ('city', models.CharField(blank=True, db_column='sCity', max_length=40)),
                ('country', models.CharField(blank=True, db_column='sCountry', max_length=40)),
                ('website', models.CharField(blank=True, db_column='sWebsite', max_length=60)),
                ('description', models.TextField(blank=True, db_column='tDesc')),
                ('opportunity_amount', models.IntegerField(blank=True, db_column='nOppAmt', null=True)),
                ('generated_by', models.CharField(blank=True, db_column='sGenBy', max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='dCreatedOn')),
                ('enquiry_type', models.CharField(blank=True, db_column='sEnqType', max_length=40)),
                ('industry', models.CharField(blank=True, choices=[('ADVERTISING', 'ADVERTISING'), ('REAL_ESTATE', 'REAL_ESTATE'), ('RETAIL', 'RETAIL'), ('AUTOMOTIVE', 'AUTOMOTIVE'), ('BANKING', 'BANKING'), ('CONTRACTING', 'CONTRACTING'), ('DISTRIBUTOR', 'DISTRIBUTOR'), ('SERVICES', 'SERVICES'), ('OTHERS', 'OTHERS')], db_column='sIndstry', max_length=20)),
            ],
            options={
                'verbose_name': 'b1.Lead',
                'db_table': 'CRMLED',
            },
        ),
        migrations.CreateModel(
            name='CRMOpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(db_column='sOppName', max_length=255)),
                ('currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], db_column='sCurr', max_length=3)),
                ('amount', models.IntegerField(blank=True, db_column='nAmt', default=0)),
                ('probability', models.IntegerField(db_column='nProb', default=0)),
                ('description', models.TextField(blank=True, db_column='tDesc')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='dtCreatedOn')),
                ('target_date', models.DateField(blank=True, db_column='dTrgtdte', null=True)),
                ('closed_on', models.DateField(blank=True, db_column='dClosedOn', null=True)),
                ('lead', models.ForeignKey(blank=True, db_column='IdLed', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.crmled')),
            ],
            options={
                'verbose_name': 'b2.Opportunity',
                'db_table': 'CRMOPP',
            },
        ),
        migrations.CreateModel(
            name='CRMPil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(db_column='sPilName', max_length=255)),
                ('target_days', models.IntegerField(db_column='nAllwDur', default=0)),
                ('probability_percent', models.IntegerField(db_column='nProbPerc', default=0)),
                ('is_active', models.BooleanField(db_column='bIsActive', default=False)),
            ],
            options={
                'verbose_name': 'a4.Pipeline Setup',
                'db_table': 'CRMPIL',
            },
        ),
        migrations.CreateModel(
            name='MASCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.IntegerField(db_column='nGrpNo', null=True)),
                ('category_name', models.CharField(blank=True, db_column='sGrpName', max_length=20)),
                ('system_code', models.CharField(blank=True, db_column='sSysNo', max_length=2, null=True)),
                ('program_code', models.CharField(blank=True, db_column='sPrgCode', max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'a8.Category Master',
                'db_table': 'MASCAT',
                'ordering': ['category_code'],
            },
        ),
        migrations.CreateModel(
            name='MASDiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(db_column='sBuName', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MASLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(db_column='sLanguage', max_length=40)),
            ],
            options={
                'verbose_name': 'a9.Language',
                'db_table': 'MASLAN',
            },
        ),
        migrations.CreateModel(
            name='MASSlm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='sFrstNm', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='sLstNm', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, db_column='sMobile', max_length=30, null=True)),
                ('telephone', models.CharField(blank=True, db_column='stelephn', max_length=30, null=True)),
                ('email', models.EmailField(db_column='eEmail', max_length=255)),
            ],
            options={
                'verbose_name': 'a6.Sales Person',
                'db_table': 'MASSLM',
            },
        ),
        migrations.CreateModel(
            name='MASUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(db_column='sUomName', max_length=5)),
                ('measure_type', models.CharField(choices=[('1', 'Count'), ('2', 'Area'), ('3', 'Volume'), ('4', 'Weight'), ('5', 'Time')], db_column='sUomType', default='1', max_length=1)),
                ('unit_desc', models.CharField(blank=True, db_column='sDesc', max_length=25)),
            ],
            options={
                'verbose_name': 'd1.UoM Master',
                'db_table': 'MASUOM',
            },
        ),
        migrations.CreateModel(
            name='CRMTsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(blank=True, db_column='dTskDt', null=True)),
                ('task_type', models.CharField(choices=[('call', 'Call'), ('telephone call', 'TelePhone Call'), ('email', 'Email'), ('visit', 'Visit'), ('meeting', 'Meeting'), ('demo', 'Demo')], db_column='sTskType', max_length=25)),
                ('task_notes', models.TextField(db_column='tTskNts', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_column='sStatus', max_length=25)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_column='sPriorty', max_length=25)),
                ('due_date', models.DateField(blank=True, db_column='dduedt', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='dtCreatedOn')),
                ('lead', models.ForeignKey(db_column='IdLed', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.crmled')),
                ('opportunity', models.ForeignKey(db_column='IdOpp', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.crmopp')),
            ],
            options={
                'verbose_name': 'b3.Task',
                'db_table': 'CRMTSK',
            },
        ),
        migrations.AddField(
            model_name='crmopp',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, db_column='IdPil', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.crmpil'),
        ),
        migrations.AddField(
            model_name='crmled',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='IdSlm', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.masslm'),
        ),
        migrations.AddField(
            model_name='crmled',
            name='language',
            field=models.ForeignKey(blank=True, db_column='IdLan', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.maslan'),
        ),
        migrations.AddField(
            model_name='crmled',
            name='pipeline',
            field=models.ForeignKey(blank=True, db_column='IdPil', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.crmpil'),
        ),
        migrations.CreateModel(
            name='CRMInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, db_column='sItmCode', max_length=19, null=True)),
                ('tax_percent', models.DecimalField(db_column='fTaxPerc', decimal_places=2, default='0.05', max_digits=2)),
                ('item_name', models.CharField(blank=True, db_column='sDesc', max_length=50, null=True)),
                ('add_desc', models.CharField(blank=True, db_column='sAddDesc', max_length=50, null=True)),
                ('gl_code', models.IntegerField(blank=True, db_column='nGLCode', null=True)),
                ('current_stock', models.FloatField(blank=True, db_column='fCurStk', null=True)),
                ('reserve_stock', models.FloatField(blank=True, db_column='fResStk', null=True)),
                ('average_cost', models.FloatField(blank=True, db_column='fCostAvg', null=True)),
                ('market_cost', models.FloatField(blank=True, db_column='fCostMkt', null=True)),
                ('sell_price', models.FloatField(blank=True, db_column='fSellPrice', null=True)),
                ('category1', models.ForeignKey(blank=True, db_column='IdInvCat1', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.mascat')),
                ('category2', models.ForeignKey(blank=True, db_column='IdInvCat2', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invcat2', to='crmapp.mascat')),
                ('category3', models.ForeignKey(blank=True, db_column='IdInvCat3', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invcat3', to='crmapp.mascat')),
                ('division', models.ForeignKey(db_column='IdDivInv', null=True, on_delete=django.db.models.deletion.PROTECT, to='crmapp.masdiv')),
                ('primary_uom', models.ForeignKey(blank=True, db_column='IDPrimUnit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crmapp.masuom')),
            ],
            options={
                'verbose_name': 'a3.Product Master',
                'db_table': 'CRMINV',
            },
        ),
    ]
